### ISSUE TITLE
Problem with code.google.com

### ISSUE THREAD

**Issue by ManUnix** [Ajnasz/grwatcher#4] opened 2011-06-10 12:24 UTC
After grwatcher logs in to google.com to get the unread feeds, the site http://code.google.com isn't accessable anymore (it loads forever.)
Subdirectories raise a "Error 500" message (e.g. http://code.google.com/hosting/) instead.
I'm using grwatcher on a german Windows XP and Arch Linux with Firefox 4.0.1 and was able to reproduce it in version 1.4.1 and the latest development version.

To workaround this problem I have to sign out on google.com (google.de has no idea grwatcher logged me in on google.com) or sign in on google.de.
After that I am able to use code.google.com normally until grwatcher checks for unread feeds again.

**Comment by Ajnasz** [comment] 2011-06-10 12:33
Is your google account a regular google account or a hosted one, using google apps?

**Comment by ManUnix** [comment] 2011-06-10 12:41
It's a regular gmail.com/googlemail.com account.

**Comment by Ajnasz** [comment] 2011-06-11 15:50
On Fri, 2011-Jun-10 at 05:41, ManUnix wrote:

> It's a regular gmail.com/googlemail.com account.

What happens if you create a new profile in Firefox and install the extension? Do you still have the issue?
Or maybe it can help if you delete the cookies.

**Comment by ManUnix** [comment] 2011-06-11 18:16
I created a new profile and installed the extension. After that I restarted firefox, typed in my login credentials into the extension settings and restarted firefox again. Then the extension checked for unread feeds and I browsed code.google.com. Same problem.
After removing all cookies and checking code.google.com, it worked fine.

I tracked it down to the "SID" cookie of google.com. When I delete it, I'm able to access code.google.com.
So there seems to be a conflict between this cookie (which is created by the extension) and the code-page.

**Comment by Ajnasz** [comment] 2011-06-12 12:37
On Sat, 2011-Jun-11 at 11:16, ManUnix wrote:

> I created a new profile and installed the extension. After that I restarted firefox, typed in my login credentials into the extension settings and restarted firefox again. Then the extension checked for unread feeds and I browsed code.google.com. Same problem.
> After removing all cookies and checking code.google.com, it worked fine.
> 
> I tracked it down to the "SID" cookie of google.com. When I delete it, I'm able to access code.google.com.
> So there seems to be a conflict between this cookie (which is created by the extension) and the code-page.

I was able to reproduce the issue. It happens only if you check the Force login option in the accounts tab. If you uncheck it, the issue should disappear.
Anyway, it seems that it doesn't work very well, so for example when you open Google Reader, you won't be logged in with the right account :. That feature might will be removed, because I don't see any solution
for that.

Are you using more than one google account? If no, you can uncheck this option, until I fix it.

## 

Lajos Koszti

**Comment by ManUnix** [comment] 2011-06-12 13:38
I'm just using one account and unchecking the force option made a difference for the current browser session.
It still doesn't fix the problem right after the browser has started. This can be fixed if I log in to google and check "stay signed in", but normally I only sign in when I need to.

It certainly shouldn't occur that signing in to google isn't the first task in the daily workflow, so this behaviour should be fine ;-)

Thanks!

**Comment by Ajnasz** [comment] 2011-06-14 17:57
I was working on it a bit, could you try this please?
http://ajnasz.hu/files/dev/grwatcher.xpi

**Comment by ManUnix** [comment] 2011-06-14 18:25
Very nice, this one solves the problem :)

**Comment by Ajnasz** [comment] 2011-06-14 19:38
Cool, than I close the issue. I already uploaded the extension to amo.

**Closed as completed by Ajnasz** 2011-06-14 19:38 UTC
