### ISSUE TITLE
No longer functions

### ISSUE THREAD

**Issue by Heptite** [Ajnasz/grwatcher#3] opened 2011-05-29 20:08 UTC
After functioning properly for several months, Google Reader Watcher has stopped displaying any unread counts for me, ever, even if I manually ask it to check for updates when I know there are unread feeds.

It is possible something has changed to cause this issue, but as far as I know nothing has changed.

Windows 7 Ultimate, Firefox 4.0.1

**Comment by Heptite** [comment] 2011-05-29 20:46
Okay, I just went through all my unread feeds and about ten minutes later it /did/ notify me (correctly) of one new unread story.  Any idea what's going on?

**Comment by Ajnasz** [comment] 2011-05-30 07:20
Currently not. If you will have the issue again, please take a look at the error console (Tools/Error Console or press Shift + Ctrl + J) and try to find errors which is related to the GRW.

**Comment by Ajnasz** [comment] 2011-06-14 19:42
Hey,

Were you able to reproduce the issue, or I can close the ticket?

**Comment by Heptite** [comment] 2011-06-14 19:45
I have had it happen once since, but I still can't figure out what causes it.  My best guess--and not a very good guess at that--is that it happens when someone I'm following shares a story, and the problem clears up when I mark the story read.

**Comment by Ajnasz** [comment] 2011-06-14 21:01
Is there any special char in his/her name maybe, what isn't handled perfectly?
Or maybe she/he has a special account or shared something special?

Unfortunately, I don't know what could be. Anyway, a new release will come soon (once it's accepted on AMO), and we will see, maybe it will fix your issue too

**Comment by JBowness** [comment] 2011-06-22 18:26
I'm experiencing the same (similar?) issue with the latest GRWatcher + Firefox 5.  It shows zero unread feeds on the addon toolbar, but the mouseover shows each of my feeds with a # of unread stories.

http://i.imgur.com/wZsko.jpg

Thanks for the great addon, and all your hard work!

**Comment by Ajnasz** [comment] 2011-06-22 20:13
I already know about the issue and.uploaded the fixed version to AMO, it
will be approved soon.

## 

Lajos Koszti

**Comment by JBowness** [comment] 2011-06-22 21:26
Awesome!  Thanks again, this is an addon I'd have trouble living without  :o)

**Comment by Heptite** [comment] 2011-08-12 22:30
Okay, I've been noticing that it stops properly reporting unread feed count whenever someone I'm following on Google Reader shares something, until I've marked what they shared as read.

**Comment by Heptite** [comment] 2011-09-06 22:48
Is this thread even being paid attention to any more?

This greasemonkey userscript has a feature to show Google Reader's unread counts while on Google pages, and it _never_ gets it wrong: http://userscripts.org/scripts/show/106067

**Comment by Ajnasz** [comment] 2011-09-07 07:49
I still can't reproduce the issue, however I follow people.

A userscript more simpler than an extension. It doesn't need to pay attention about login and windows and menus and some other things. :)

**Comment by Ajnasz** [comment] 2011-11-13 13:12
Could you please try out the development version: http://ajnasz.hu/files/dev/grwatcher.xpi

I'm planning to upload it to AMO on next week and I want to know if you still have the issue.

Thanks

**Comment by Heptite** [comment] 2011-11-13 18:52
I have it installed, but since the problem can go dormant for sometimes days at a time, I will not know right away if the problem is fixed.

**Comment by Heptite** [comment] 2011-11-19 06:40
So far it has been working without failing to report new feed stories, although I have noticed that it can now take a while to update--somewhere between ten and thirty seconds. It's not really a problem for me, but I figured I should report it.

**Comment by Ajnasz** [comment] 2011-11-19 11:09
Thanks, then I close the issue

The other issue is probably caching by the Google Reader side.

Thanks again

**Closed as completed by Ajnasz** 2011-11-19 11:09 UTC
